-- INSERT RECORDS (Enriched with Country and Canton)
INSERT INTO property_listings (title, description, price, bedrooms, city, country, canton) VALUES
('Sunny Apartment in Zurich-Oerlikon', 'Bright 3.5 room apartment located near the Hallenstadion. Excellent public transport connections to the airport and city center. diverse neighborhood with many shops.', 2800.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('Industrial Style Loft in Zurich West', 'Trendy open-space loft in a converted factory. High ceilings, exposed concrete, and a rooftop terrace. Perfect for young creatives or a startup couple.', 3900.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Exclusive Penthouse on Zurichberg', 'Top-floor residence with breathtaking views of the city and the Alps. Features a private elevator, fireplace, and a wrap-around terrace. Absolute privacy and luxury.', 9500.0, 3, 'Zurich', 'Switzerland', 'Zurich'),
('Student Room in Shared Flat', 'Affordable room in a lively 4-person WG in Zurich-Wiedikon. Close to bars, cafes, and nightlife. Shared kitchen and living room.', 850.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Historic Townhouse in Niederdorf', 'Live in the middle of the old town. A unique 4-story house with exposed beams and historic charm. Steps away from the Limmat river and Grossmunster.', 5200.0, 3, 'Zurich', 'Switzerland', 'Zurich'),
('Modern Flat near United Nations', 'Sleek and secure 2-bedroom apartment walking distance from the UN headquarters. Concierge service and gym in the building. Ideal for diplomats.', 4800.0, 2, 'Geneva', 'Switzerland', 'Geneva'),
('Spacious Family Apartment in Champel', 'Quiet and green neighborhood. Large 5-room apartment with a renovated kitchen and two balconies. Close to parks and top-rated schools.', 6200.0, 3, 'Geneva', 'Switzerland', 'Geneva'),
('Budget Studio near Cornavin', 'Small but functional studio right next to the main train station. Perfect for a commuter needing a pied-à-terre in the city center.', 1600.0, 0, 'Geneva', 'Switzerland', 'Geneva'),
('Lake View Apartment in Ouchy', 'Stunning 3-bedroom flat right on the lakeside promenade. Wake up to views of the French Alps across Lake Geneva. elegant parquet floors.', 5900.0, 3, 'Lausanne', 'Switzerland', 'Vaud'),
('Attic Apartment near Cathedral', 'Charming top-floor flat with sloping ceilings in the heart of Lausanne. No elevator, but offers a fantastic view over the rooftops.', 2100.0, 1, 'Lausanne', 'Switzerland', 'Vaud'),
('Architectural Gem near Roche Tower', 'Modern, minimalist apartment designed by a famous architect. Flooded with light, featuring high-end appliances. Walking distance to Roche campus.', 3400.0, 2, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Riverfront Flat with Rhine View', 'Directly on the Rhine river. Watch the swimmers in summer from your balcony. Spacious living room and classic herringbone flooring.', 3100.0, 2, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Medieval Charm in Bern Old Town', 'Located in a UNESCO World Heritage building. Sandstone walls, cellar storage, and view of the Zytglogge. A truly unique living experience.', 2600.0, 2, 'Bern', 'Switzerland', 'Bern'),
('Modern Garden Apartment in Kirchenfeld', 'Ground floor apartment with a large private garden in the diplomat quarter. Quiet, secure, and very prestigious neighborhood.', 4500.0, 3, 'Bern', 'Switzerland', 'Bern'),
('Luxury Chalet in Zermatt', 'Traditional wooden chalet with modern interior. Unobstructed view of the Matterhorn. Includes a sauna and ski boot heater. Available for long-term seasonal rent.', 12000.0, 4, 'Zermatt', 'Switzerland', 'Valais'),
('Lake Lugano Villa with Pool', 'Mediterranean style villa in Ticino. Features a lush garden with palm trees, an infinity pool, and private lake access. Feel like you are on vacation every day.', 14500.0, 5, 'Lugano', 'Switzerland', 'Ticino'),
('Cozy Apartment in Old Lucerne', 'Right on the Reuss river with a view of the Chapel Bridge. Historic building with modern amenities. Walkable to everything.', 2900.0, 2, 'Lucerne', 'Switzerland', 'Lucerne'),
('Remote Cabin in Grisons', 'Secluded mountain hut for nature lovers. Simple living, wood stove heating, and surrounded by forest. Accessible by 4x4 in winter.', 1200.0, 1, 'Chur', 'Switzerland', 'Grisons'),
('Commuter Friendly Flat in Olten', 'Practical and newly built apartment right at the train station hub. reach Zurich, Bern, or Basel in under 30 minutes. High standard finishing.', 1950.0, 2, 'Olten', 'Switzerland', 'Solothurn'),
('Design Loft in St. Gallen', 'Close to the Abbey library. Open concept living in a converted textile warehouse. High ceilings and huge windows.', 2300.0, 1, 'St. Gallen', 'Switzerland', 'St. Gallen'),
('Minimalist Studio in Seefeld', 'Steps from the lake, this studio features polished concrete floors and smart home integration. Perfect for a single professional working in the city.', 2200.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Family Home in Witikon', 'Located on the green edge of the city. 5.5 rooms with a large garden, double garage, and forest trails right at your doorstep. Quiet and child-friendly.', 4100.0, 4, 'Zurich', 'Switzerland', 'Zurich'),
('Renovated Altbau in Kreis 4', 'High ceilings and stucco details meet modern kitchen design. Located in the heart of the vibrant Langstrasse district, surrounded by bars and culture.', 3100.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('Lakeview Residence in Kilchberg', 'Just outside the city limits with lower taxes. Unobstructed view of Lake Zurich. Private boat mooring available upon request.', 7800.0, 3, 'Kilchberg', 'Switzerland', 'Zurich'),
('Tech-Hub Apartment in Altstetten', 'Newly built complex near the Letzipark. Energy-efficient Minergie standard, floor heating, and shared rooftop garden. Quick access to highway.', 2500.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('Artist Atelier in Binz', 'Raw industrial space with north-facing skylights. Huge open floor plan ideal for painting or sculpture work. Living and working combined.', 3400.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Garden Apartment in Wollishofen', 'Close to the Rote Fabrik and the lake. Ground floor with a private patio. Very pet-friendly building with diverse neighbors.', 2750.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('Luxury Villa on the Goldcoast', 'Exclusive property in Herrliberg with infinity pool, spa area, and wine cellar. Panoramic views of the mountains and lake.', 16500.0, 6, 'Herrliberg', 'Switzerland', 'Zurich'),
('Student Dorm near ETH Hönggerberg', 'Compact single room with ensuite bathroom. Shared massive kitchen and study halls. Shuttle bus to central campus runs every 10 minutes.', 750.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Corporate Apartment in Oerlikon', 'Fully furnished business apartment near the trade fair. Cleaning service included. Ideal for short-term project stays.', 3200.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('Suburban Bliss in Winterthur', 'Spacious semi-detached house in a blooming garden city. Good schools nearby and only 20 mins by train to Zurich HB.', 2600.0, 4, 'Winterthur', 'Switzerland', 'Zurich'),
('Old Town Loft in Winterthur', 'In the pedestrian zone of the old town. Historic charm with exposed masonry. diverse shopping and dining options immediately outside.', 2300.0, 2, 'Winterthur', 'Switzerland', 'Zurich'),
('Penthouse in Dübendorf', 'Near the innovation park and military airfield. Huge terrace, very modern finishing, and direct elevator access.', 3600.0, 3, 'Dübendorf', 'Switzerland', 'Zurich'),
('Cheap Shared Room in Schwamendingen', 'Simple room in an older building. Looking for an uncomplicated roommate. close to tram stops and shopping center.', 650.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Uetliberg View Flat', 'Perched on the slope of the Uetliberg. Quiet residential street with great hiking access. Balcony with evening sun.', 2900.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('River Limmat Apartment', 'Listen to the river flow from your bedroom. Modern apartment in the trendy Wipkingen area. Close to Letten Badi.', 3000.0, 2, 'Zurich', 'Switzerland', 'Zurich'),
('Coop Housing in Hunziker Areal', 'Sustainable living in a cooperative. innovative architecture, shared guest rooms, and mobility station.', 2100.0, 3, 'Zurich', 'Switzerland', 'Zurich'),
('Luxury Condo in Kusnacht', 'Prestigious address on the Gold Coast. Marble floors, high security, and lake access rights.', 8900.0, 4, 'Kusnacht', 'Switzerland', 'Unknown'),
('Budget Flat in Adliswil', 'Close to the Sihltal nature reserve. Quick train ride to the city. Ideal for young families on a budget.', 1950.0, 3, 'Adliswil', 'Switzerland', 'Zurich'),
('Rooftop Flat in Thalwil', 'Stunning lake views from a large terrace. Modern amenities and excellent train connections to Zurich and Zug.', 3800.0, 3, 'Thalwil', 'Switzerland', 'Zurich'),
('Bohemian Loft in Carouge', 'Located in the Greenwich Village of Geneva. Artisanal workshops nearby, wooden beams, and a cozy fireplace. Very charming atmosphere.', 3800.0, 2, 'Geneva', 'Switzerland', 'Geneva'),
('Diplomat Villa in Cologny', 'One of the most prestigious addresses in Switzerland. Gated property with high security, lake view, and manicured gardens.', 18000.0, 5, 'Geneva', 'Switzerland', 'Geneva'),
('Lakeside Condo in Nyon', 'Between Geneva and Lausanne. Modern 3-room apartment just meters from the water. Great for Paléo Festival lovers.', 2900.0, 2, 'Nyon', 'Switzerland', 'Vaud'),
('Jazz Festival Flat in Montreux', 'Belle Époque building with high ceilings and balconies facing the lake. Walk along the flower-lined promenade. Historic grandeur.', 3500.0, 3, 'Montreux', 'Switzerland', 'Vaud'),
('Vineyard House in Lavaux', 'UNESCO heritage site. Live amidst the terraced vineyards with a view of the lake. Rustic stone house with modern interior.', 4200.0, 3, 'Cully', 'Switzerland', 'Vaud'),
('Student Studio in Renens', 'Close to EPFL and UNIL. Functional layout with kitchenette. Bike storage available. Vibrant student community.', 1100.0, 1, 'Lausanne', 'Switzerland', 'Vaud'),
('Luxury Flat in Eaux-Vives', 'Close to the Jet d''Eau. Marble bathrooms, concierge service, and air conditioning. Very central and upscale.', 6500.0, 3, 'Geneva', 'Switzerland', 'Geneva'),
('Suburban House in Meyrin', 'Close to CERN. Practical family home with garage and hobby room. International school nearby.', 3900.0, 4, 'Geneva', 'Switzerland', 'Geneva'),
('Charming Apartment in Vevey', 'Close to the Charlie Chaplin museum and Nestlé HQ. Bright rooms with parquet floors. Weekly market in the town square.', 2400.0, 2, 'Vevey', 'Switzerland', 'Vaud'),
('Modern Condo in Morges', 'View of Mont Blanc on clear days. Tulip festival in spring. Quiet residential area with good train connections.', 2700.0, 2, 'Morges', 'Switzerland', 'Vaud'),
('Old Town Flat in Geneva', 'Historic building near St. Pierre Cathedral. Narrow streets, cobblestones, and authentic charm. No elevator.', 3200.0, 2, 'Geneva', 'Switzerland', 'Geneva'),
('Ski Chalet in Villars', 'Year-round destination in Vaud Alps. International schools nearby. Cozy wood interior with fireplace.', 4500.0, 4, 'Villars-sur-Ollon', 'Switzerland', 'Vaud'),
('Serviced Apartment near Airport', 'Perfect for frequent flyers. Cleaning and laundry service included. Shuttle to GVA airport.', 2800.0, 1, 'Geneva', 'Switzerland', 'Geneva'),
('Lake House in Versoix', 'Direct lake access with a small private beach. Quiet garden setting. Ideal for water sports enthusiasts.', 7200.0, 4, 'Versoix', 'Switzerland', 'Geneva'),
('Attic in Yverdon-les-Bains', 'Near the thermal baths and Science Park. Affordable spacious living in a historic town.', 1800.0, 3, 'Yverdon', 'Switzerland', 'Vaud'),
('Artsy Flat in Kleinbasel', 'Near the Rhine promenade and Art Basel venue. lively neighborhood with diverse cuisine. High ceilings and large windows.', 2200.0, 2, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Family Apartment in Gundeldingen', 'Behind the SBB train station. lively multicultural area. 4-room apartment with balcony facing the courtyard.', 2500.0, 3, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Villa in Riehen', 'Close to the Fondation Beyeler. Green, quiet, and wealthy municipality. Large garden and swimming pool.', 5800.0, 5, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Politician''s Apartment in Breitenrain', 'Classic Bernese apartment with sandstone details. Walking distance to the Rose Garden. Quiet streets with trams nearby.', 2800.0, 3, 'Bern', 'Switzerland', 'Bern'),
('Trendy Loft in Lorraine', 'Former industrial area turned hipster haven. Near the Aare river for summer swimming. Graffiti art and cafes nearby.', 2100.0, 1, 'Bern', 'Switzerland', 'Bern'),
('Suburban Home in Köniz', 'Short commute to Bern center. Large family house with solar panels and heat pump. Near Gurten mountain for hiking.', 3200.0, 4, 'Bern', 'Switzerland', 'Bern'),
('River View in Aarau', 'Capital of Aargau. Beautiful old town apartment overlooking the Aare. famous gables and painted eaves.', 1900.0, 2, 'Aarau', 'Switzerland', 'Aargau'),
('Pharma Hub Apartment in Allschwil', 'Close to Basel''s biotech campus. Modern build, efficient layout, ideal for expats working in the industry.', 2300.0, 2, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Altbau in St. Johann', 'Near Novartis Campus. High ceilings, fishbone parquet, and stucco. Close to Volta Park.', 2700.0, 2, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Matte Quartier Apartment', 'Located directly at the Aare river level in Bern. Historic working-class district now very trendy.', 2400.0, 2, 'Bern', 'Switzerland', 'Bern'),
('Modern Flat in Länggasse', 'University district of Bern. Vibrant atmosphere with student cafes and bookstores. Renovated building.', 2600.0, 2, 'Bern', 'Switzerland', 'Bern'),
('Large House in Bottmingen', 'Exclusive residential area near Basel. Historic castle nearby. Huge garden and double garage.', 5200.0, 5, 'Basel', 'Switzerland', 'Basel-Stadt'),
('City Apartment in Liestal', 'Capital of Basel-Landschaft. Good train connections. Charming old town gate.', 1800.0, 3, 'Liestal', 'Switzerland', 'Basel-Landschaft'),
('Tax-Efficient Penthouse in Zug', 'Low tax municipality. Luxury finishing, view of Lake Zug and Rigi. Smart home system and private underground parking.', 6200.0, 3, 'Zug', 'Switzerland', 'Zug'),
('Family Flat in Baar', 'Close to international companies. New construction with playground in the complex. Very modern and clean.', 3500.0, 3, 'Zug', 'Switzerland', 'Zug'),
('Historic Home in Schwyz', 'Live near the Mythen mountains. Traditional architecture with wood shingles. Low taxes and close to nature.', 2100.0, 3, 'Schwyz', 'Switzerland', 'Schwyz'),
('Lakeside Villa in Kastanienbaum', 'Exclusive peninsula near Lucerne. Private lake access, boat house, and absolute tranquility. For high-net-worth individuals.', 11000.0, 5, 'Horw', 'Switzerland', 'Lucerne'),
('City Apartment in Kriens', 'At the foot of Mount Pilatus. Good connection to Lucerne center. Affordable modern apartment with balcony.', 1800.0, 2, 'Lucerne', 'Switzerland', 'Lucerne'),
('Resort Apartment in Burgenstock', 'High above Lake Lucerne. Access to resort spa and restaurants. Breathtaking views and luxury service.', 8500.0, 2, 'Ennetbürgen', 'Switzerland', 'Nidwalden'),
('Lake View in Weggis', 'Famous for its mild climate and magnolias. Unobstructed view of the lake and mountains.', 3400.0, 3, 'Weggis', 'Switzerland', 'Lucerne'),
('Modern Flat in Rotkreuz', 'Important train hub and business district. Modern architecture and good infrastructure.', 2600.0, 2, 'Rotkreuz', 'Switzerland', 'Zug'),
('Chalet in Engelberg', 'Mountain lifestyle near the monastery. Great skiing and hiking. Wood interior.', 2200.0, 3, 'Engelberg', 'Switzerland', 'Obwalden'),
('Apartment in Sursee', 'Overlooking the Sempachersee. Historic old town and modern shopping centers.', 1900.0, 3, 'Sursee', 'Switzerland', 'Lucerne'),
('Rustico in Valle Verzasca', 'Traditional stone house in the valley. River with crystal clear water nearby. Perfect summer retreat or holiday home.', 1500.0, 2, 'Lavertezzo', 'Switzerland', 'Ticino'),
('Modern Flat in Bellinzona', 'View of the three castles (UNESCO). Capital of Ticino. Warm climate and Italian flair. Good train hub.', 1700.0, 3, 'Bellinzona', 'Switzerland', 'Ticino'),
('Promenade Apartment in Ascona', 'Right on the famous lake promenade. Restaurants and gelaterias downstairs. Jazz festival in summer.', 3200.0, 2, 'Ascona', 'Switzerland', 'Ticino'),
('Luxury Villa in Morcote', 'Voted most beautiful village in Switzerland. Lakefront villa with botanical garden style landscaping.', 9800.0, 4, 'Lugano', 'Switzerland', 'Ticino'),
('City Flat in Locarno', 'Close to the Piazza Grande and film festival. Sunny balcony, palm trees in the garden. Mild winters.', 2100.0, 2, 'Locarno', 'Switzerland', 'Ticino'),
('Hilltop House in Brè', 'High above Lugano city. Funicular access. Spectacular sunrises and cooler air in summer.', 3600.0, 3, 'Lugano', 'Switzerland', 'Ticino'),
('Grotto Style House in Mendrisio', 'Near the FoxTown outlet and vineyards. Stone cellar perfect for wine storage. Rustic charm.', 1800.0, 3, 'Mendrisio', 'Switzerland', 'Ticino'),
('Lakeside Flat in Paradiso', 'Upscale municipality bordering Lugano. View of the bay and San Salvatore. Concierge service.', 4500.0, 3, 'Lugano', 'Switzerland', 'Ticino'),
('High-End Chalet in Gstaad', 'Celebrity hotspot. Traditional exterior, ultra-luxury interior. Indoor pool, cinema, and staff quarters.', 25000.0, 6, 'Gstaad', 'Switzerland', 'Bern'),
('Ski-in Ski-out in St. Moritz', 'Direct access to the slopes. Corviglia view. Champagne climate and exclusive boutiques nearby.', 9500.0, 3, 'St. Moritz', 'Switzerland', 'Grisons'),
('Freeride Apartment in Andermatt', 'Newly developed resort area. Chedi hotel nearby. Modern alpine design with wood and stone.', 4500.0, 3, 'Andermatt', 'Switzerland', 'Uri'),
('Family Chalet in Davos', 'Highest town in Europe. Near the congress center and Parsenn ski area. Spacious wood construction.', 3800.0, 4, 'Davos', 'Switzerland', 'Grisons'),
('Sunny Flat in Crans-Montana', 'On a high plateau with south-facing golf course views. French-speaking luxury resort. Casino and shopping.', 4100.0, 3, 'Crans-Montana', 'Switzerland', 'Valais'),
('Après-Ski Pad in Verbier', 'Close to the main lift and nightlife. Cozy fireplace, wooden interior, and balcony with mountain view.', 5200.0, 2, 'Verbier', 'Switzerland', 'Valais'),
('Glacier View in Saas-Fee', 'Car-free village. View of the Dom and glaciers. Traditional Walliser Stadel architecture converted to living space.', 2400.0, 2, 'Saas-Fee', 'Switzerland', 'Valais'),
('Nature Retreat in Arosa', 'End of the valley. Bear sanctuary and hiking trails. Quiet apartment with fireplace. Train access via winding route.', 2200.0, 2, 'Arosa', 'Switzerland', 'Grisons'),
('Valley Home in Grindelwald', 'At the foot of the Eiger North Face. Tourist hotspot but cozy living. Chalet style with flower boxes.', 2900.0, 3, 'Grindelwald', 'Switzerland', 'Bern'),
('Budget Ski Apartment in Engelberg', 'Famous for the Titlis mountain. simple apartment for freeriders and monks. Close to the monastery.', 1600.0, 1, 'Engelberg', 'Switzerland', 'Obwalden'),
('Thermal Bath Apartment in Leukerbad', 'Largest thermal spa resort in the Alps. Apartment has direct tunnel access to the baths.', 1700.0, 2, 'Leukerbad', 'Switzerland', 'Valais'),
('Apartment in Flims', 'Close to the Caumasee and ski lifts. Modern architecture blending with nature.', 2500.0, 2, 'Flims', 'Switzerland', 'Grisons'),
('Textile Loft in St. Gallen', 'converted industrial space near the university. High ceilings, large windows, creative atmosphere.', 2100.0, 1, 'St. Gallen', 'Switzerland', 'St. Gallen'),
('Lake Constance View in Rorschach', 'Directly on the Bodensee. Watch the ferries to Germany. Affordable lakeside living.', 1750.0, 2, 'Rorschach', 'Switzerland', 'St. Gallen'),
('Quiet Home in Appenzell', 'Traditional painted house in the village center. Close to Alpstein hiking. Very conservative and safe area.', 1900.0, 3, 'Appenzell', 'Switzerland', 'Appenzell Innerrhoden'),
('Commuter Hub in Olten', 'The central rail crossroad of Switzerland. Reach anywhere fast. Modern functional apartment.', 1850.0, 2, 'Olten', 'Switzerland', 'Solothurn'),
('Watch Valley Flat in La Chaux-de-Fonds', 'UNESCO site for town planning. Checkboard street layout. Affordable large apartments in Art Nouveau style.', 1400.0, 3, 'La Chaux-de-Fonds', 'Switzerland', 'Neuchâtel'),
('Bilingual City Flat in Biel/Bienne', 'Near the lake and Omega headquarters. French and German spoken here. lively alternative culture scene.', 1650.0, 2, 'Biel/Bienne', 'Switzerland', 'Bern'),
('Castle View in Thun', 'Gateway to the Bernese Oberland. Aare river surfing nearby. Historic town center with a massive castle.', 2000.0, 2, 'Thun', 'Switzerland', 'Bern'),
('Riverside in Solothurn', 'Baroque architecture. St. Ursus Cathedral view. Many bars along the Aare river. Cultural film days.', 1800.0, 2, 'Solothurn', 'Switzerland', 'Solothurn'),
('Technopark Flat in Zurich-West', 'Live where the startups are. Prime Tower view. Puls 5 shopping and fitness nearby.', 3100.0, 1, 'Zurich', 'Switzerland', 'Zurich'),
('Garden City in Munchenstein', 'Near Basel. Green and spacious. close to the Schaulager art museum.', 2400.0, 3, 'Basel', 'Switzerland', 'Basel-Stadt'),
('Historic Loft in Baden', 'Former spa town. Thermal baths nearby. Grand casino and industrial history combined.', 2600.0, 2, 'Baden', 'Switzerland', 'Unknown'),
('Countryside Farmhouse in Emmental', 'Rolling hills and cheese production. massive wooden farmhouse with a stove. 30 mins to Bern.', 2200.0, 5, 'Langnau', 'Switzerland', 'Bern'),
('Modern Flat in Frauenfeld', 'Capital of Thurgau. Sugar factory nearby. Affordable rents and good train connection to Zurich.', 1800.0, 3, 'Frauenfeld', 'Switzerland', 'Thurgau'),
('Lake View in Spiez', 'Bay of Europe. Castle and vineyards on the lake. Quiet retirement or family spot.', 2500.0, 3, 'Spiez', 'Switzerland', 'Bern'),
('Alpine City in Brig', 'Hub for Zermatt and Italy. Stockalper Palace. Sunny valley floor.', 1600.0, 3, 'Brig', 'Switzerland', 'Valais'),
('Border Town Flat in Kreuzlingen', 'Next to Constance (Germany). Cheap shopping across the border. Lake Constance park.', 1700.0, 2, 'Kreuzlingen', 'Switzerland', 'Thurgau'),
('Rheinfall View in Neuhausen', 'Hear the roar of Europe''s largest waterfall. Tourist area but spectacular nature.', 1800.0, 2, 'Neuhausen', 'Switzerland', 'Schaffhausen'),
('Abbey View in Einsiedeln', 'Pilgrimage site with a massive monastery. Winter sport and hiking nearby.', 1950.0, 3, 'Einsiedeln', 'Switzerland', 'Schwyz'),
('Modern Living in Chur', 'Oldest city in Switzerland. Gateway to the Grisons mountains. Urban living with mountain views.', 2100.0, 2, 'Chur', 'Switzerland', 'Grisons'),
('Lakeside in Murten', 'Medieval walled town on Lake Murten. Bilingual area. Great water sports and history.', 2300.0, 3, 'Murten', 'Switzerland', 'Fribourg'),
('Cozy Residence in Martigny', 'Private garden and patio area. Pet friendly. Surrounded by nature, perfect for outdoor enthusiasts.', 10034.0, 3.5, 'Martigny', 'Switzerland', 'Valais'),
('Stylish Studio in Grenchen', 'Luxury amenities including concierge service and gym access. Located in a quiet neighborhood with easy access to public transport.', 14165.0, 4, 'Grenchen', 'Switzerland', 'Solothurn'),
('Central Studio in Interlaken', 'Luxury amenities including concierge service and gym access. Spacious living room with fireplace and open plan kitchen.', 8876.0, 4, 'Interlaken', 'Switzerland', 'Bern'),
('Affordable Flat in Rapperswil-Jona', 'Charming old building with high ceilings and stucco details. Luxury amenities including concierge service and gym access.', 8135.0, 2, 'Rapperswil-Jona', 'Switzerland', 'St. Gallen'),
('Charming Garden Apartment in Brugg', 'Features a modern kitchen, large balcony, and underground parking. Cozy retreat for weekend getaways or permanent living.', 8105.0, 4.5, 'Brugg', 'Switzerland', 'Aargau'),
('Elegant Residence in Sierre', 'Private garden and patio area. Pet friendly. Private garden and patio area. Pet friendly.', 7017.0, 2, 'Sierre', 'Switzerland', 'Valais'),
('Exclusive Terrace Flat in Chiasso', 'Luxury amenities including concierge service and gym access. Located in a quiet neighborhood with easy access to public transport.', 3443.0, 4, 'Chiasso', 'Switzerland', 'Ticino'),
('Exclusive Loft in Sierre', 'Ideal for families or professionals. Close to schools and shops. Ideal for families or professionals. Close to schools and shops.', 11454.0, 2, 'Sierre', 'Switzerland', 'Valais'),
('Minimalist Villa in Morges', 'Smart home features and energy efficient construction. Located in a quiet neighborhood with easy access to public transport.', 12116.0, 2.5, 'Morges', 'Switzerland', 'Vaud'),
('Elegant Maisonette in Baden', 'Luxury amenities including concierge service and gym access. Smart home features and energy efficient construction.', 8098.0, 5, 'Baden', 'Switzerland', 'Aargau'),
('Affordable Villa in Brugg', 'Smart home features and energy efficient construction. Features a modern kitchen, large balcony, and underground parking.', 5660.0, 3.5, 'Brugg', 'Switzerland', 'Aargau'),
('Traditional Garden Apartment in Herisau', 'Charming old building with high ceilings and stucco details. Smart home features and energy efficient construction.', 14034.0, 1, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Stylish Villa in Stans', 'Ideal for families or professionals. Close to schools and shops. Features a modern kitchen, large balcony, and underground parking.', 10540.0, 3.5, 'Stans', 'Switzerland', 'Nidwalden'),
('Quiet Penthouse in Schaffhausen', 'In the heart of the city, walking distance to the train station. Spacious living room with fireplace and open plan kitchen.', 8933.0, 2, 'Schaffhausen', 'Switzerland', 'Schaffhausen'),
('Quiet Penthouse in Brugg', 'Cozy retreat for weekend getaways or permanent living. Luxury amenities including concierge service and gym access.', 1508.0, 3.5, 'Brugg', 'Switzerland', 'Aargau'),
('Elegant Duplex in Neuchâtel', 'Ideal for families or professionals. Close to schools and shops. Located in a quiet neighborhood with easy access to public transport.', 9986.0, 1, 'Neuchâtel', 'Switzerland', 'Neuchâtel'),
('Quiet Villa in Sarnen', 'Bright rooms with floor-to-ceiling windows. Bright rooms with floor-to-ceiling windows.', 7072.0, 3.5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Rustic Attic in Neuchâtel', 'Surrounded by nature, perfect for outdoor enthusiasts. Cozy retreat for weekend getaways or permanent living.', 12705.0, 4.5, 'Neuchâtel', 'Switzerland', 'Neuchâtel'),
('Quiet Attic in Landquart', 'Spacious living room with fireplace and open plan kitchen. Cozy retreat for weekend getaways or permanent living.', 13903.0, 4, 'Landquart', 'Switzerland', 'Grisons'),
('Affordable Garden Apartment in Martigny', 'Located in a quiet neighborhood with easy access to public transport. Top floor with elevator and panoramic terrace.', 2641.0, 2.5, 'Martigny', 'Switzerland', 'Valais'),
('Exclusive Attic in Brugg', 'Smart home features and energy efficient construction. Top floor with elevator and panoramic terrace.', 6570.0, 4, 'Brugg', 'Switzerland', 'Aargau'),
('Minimalist Duplex in Grenchen', 'In the heart of the city, walking distance to the train station. Cozy retreat for weekend getaways or permanent living.', 1657.0, 1.5, 'Grenchen', 'Switzerland', 'Solothurn'),
('Historic Garden Apartment in Glarus', 'Smart home features and energy efficient construction. In the heart of the city, walking distance to the train station.', 8356.0, 3.5, 'Glarus', 'Switzerland', 'Glarus'),
('Sunny Terrace Flat in Davos', 'Cozy retreat for weekend getaways or permanent living. Bright rooms with floor-to-ceiling windows.', 5784.0, 1, 'Davos', 'Switzerland', 'Grisons'),
('Bright Attic in Fribourg', 'Top floor with elevator and panoramic terrace. Located in a quiet neighborhood with easy access to public transport.', 11878.0, 4.5, 'Fribourg', 'Switzerland', 'Fribourg'),
('Charming Villa in Sarnen', 'Top floor with elevator and panoramic terrace. Features a modern kitchen, large balcony, and underground parking.', 8383.0, 2.5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Industrial Garden Apartment in Rapperswil-Jona', 'Recently renovated with attention to detail. Wood floors throughout. Stunning views of the mountains and lake. High-end finishing.', 1689.0, 3.5, 'Rapperswil-Jona', 'Switzerland', 'St. Gallen'),
('Minimalist Flat in Altdorf', 'Stunning views of the mountains and lake. High-end finishing. Private garden and patio area. Pet friendly.', 4688.0, 1.5, 'Altdorf', 'Switzerland', 'Uri'),
('Exclusive Attic in Bülach', 'Private garden and patio area. Pet friendly. Smart home features and energy efficient construction.', 9407.0, 1, 'Bülach', 'Switzerland', 'Zurich'),
('Sunny Garden Apartment in Davos', 'Features a modern kitchen, large balcony, and underground parking. Smart home features and energy efficient construction.', 8839.0, 3.5, 'Davos', 'Switzerland', 'Grisons'),
('Rustic Duplex in Locarno', 'Private garden and patio area. Pet friendly. Located in a quiet neighborhood with easy access to public transport.', 3964.0, 2.5, 'Locarno', 'Switzerland', 'Ticino'),
('Spacious Garden Apartment in Herisau', 'Stunning views of the mountains and lake. High-end finishing. Smart home features and energy efficient construction.', 5988.0, 3, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Luxury Studio in Landquart', 'Surrounded by nature, perfect for outdoor enthusiasts. Bright rooms with floor-to-ceiling windows.', 10334.0, 2.5, 'Landquart', 'Switzerland', 'Grisons'),
('Bright Flat in Neuchâtel', 'Recently renovated with attention to detail. Wood floors throughout. Cozy retreat for weekend getaways or permanent living.', 7762.0, 2.5, 'Neuchâtel', 'Switzerland', 'Neuchâtel'),
('Central Studio in Fribourg', 'Top floor with elevator and panoramic terrace. Top floor with elevator and panoramic terrace.', 7242.0, 3, 'Fribourg', 'Switzerland', 'Fribourg'),
('Exclusive Terrace Flat in Glarus', 'Top floor with elevator and panoramic terrace. Stunning views of the mountains and lake. High-end finishing.', 11303.0, 2, 'Glarus', 'Switzerland', 'Glarus'),
('Exclusive Attic in Schaffhausen', 'Bright rooms with floor-to-ceiling windows. Spacious living room with fireplace and open plan kitchen.', 8802.0, 2, 'Schaffhausen', 'Switzerland', 'Schaffhausen'),
('Historic Garden Apartment in Herisau', 'Smart home features and energy efficient construction. Cozy retreat for weekend getaways or permanent living.', 8145.0, 4.5, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Cozy Villa in Schaffhausen', 'In the heart of the city, walking distance to the train station. Private garden and patio area. Pet friendly.', 9824.0, 4, 'Schaffhausen', 'Switzerland', 'Schaffhausen'),
('Affordable Terrace Flat in Kloten', 'Surrounded by nature, perfect for outdoor enthusiasts. Stunning views of the mountains and lake. High-end finishing.', 2189.0, 3.5, 'Kloten', 'Switzerland', 'Zurich'),
('Stylish Penthouse in Sarnen', 'Bright rooms with floor-to-ceiling windows. Smart home features and energy efficient construction.', 14772.0, 2.5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Minimalist Residence in Zug', 'Spacious living room with fireplace and open plan kitchen. Features a modern kitchen, large balcony, and underground parking.', 14233.0, 3, 'Zug', 'Switzerland', 'Zug'),
('Elegant Apartment in Grenchen', 'Charming old building with high ceilings and stucco details. Located in a quiet neighborhood with easy access to public transport.', 4712.0, 3.5, 'Grenchen', 'Switzerland', 'Solothurn'),
('Rustic Penthouse in Landquart', 'Charming old building with high ceilings and stucco details. Recently renovated with attention to detail. Wood floors throughout.', 11929.0, 3.5, 'Landquart', 'Switzerland', 'Grisons'),
('Stylish Penthouse in Landquart', 'Spacious living room with fireplace and open plan kitchen. Top floor with elevator and panoramic terrace.', 1204.0, 3.5, 'Landquart', 'Switzerland', 'Grisons'),
('Quiet Residence in Rapperswil-Jona', 'Bright rooms with floor-to-ceiling windows. Private garden and patio area. Pet friendly.', 14920.0, 4, 'Rapperswil-Jona', 'Switzerland', 'St. Gallen'),
('Bright Residence in Sarnen', 'In the heart of the city, walking distance to the train station. Features a modern kitchen, large balcony, and underground parking.', 3575.0, 1.5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Charming Apartment in Fribourg', 'Spacious living room with fireplace and open plan kitchen. Surrounded by nature, perfect for outdoor enthusiasts.', 5924.0, 2.5, 'Fribourg', 'Switzerland', 'Fribourg'),
('Charming Flat in Delémont', 'Private garden and patio area. Pet friendly. Bright rooms with floor-to-ceiling windows.', 3599.0, 5, 'Delémont', 'Switzerland', 'Jura'),
('Spacious Studio in Herisau', 'Features a modern kitchen, large balcony, and underground parking. Top floor with elevator and panoramic terrace.', 13634.0, 1, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Elegant Chalet in Zug', 'Located in a quiet neighborhood with easy access to public transport. Cozy retreat for weekend getaways or permanent living.', 2059.0, 4, 'Zug', 'Switzerland', 'Zug'),
('Luxury Attic in Sion', 'Private garden and patio area. Pet friendly. Private garden and patio area. Pet friendly.', 10921.0, 3.5, 'Sion', 'Switzerland', 'Valais'),
('Bright Villa in Schaffhausen', 'Cozy retreat for weekend getaways or permanent living. Cozy retreat for weekend getaways or permanent living.', 4869.0, 4, 'Schaffhausen', 'Switzerland', 'Schaffhausen'),
('Cozy Penthouse in Sierre', 'Features a modern kitchen, large balcony, and underground parking. Located in a quiet neighborhood with easy access to public transport.', 6247.0, 3, 'Sierre', 'Switzerland', 'Valais'),
('Cozy Garden Apartment in Davos', 'Features a modern kitchen, large balcony, and underground parking. Stunning views of the mountains and lake. High-end finishing.', 4396.0, 1.5, 'Davos', 'Switzerland', 'Grisons'),
('Central House in Delémont', 'Spacious living room with fireplace and open plan kitchen. Ideal for families or professionals. Close to schools and shops.', 9153.0, 5, 'Delémont', 'Switzerland', 'Jura'),
('Minimalist Duplex in Bülach', 'Surrounded by nature, perfect for outdoor enthusiasts. Bright rooms with floor-to-ceiling windows.', 1335.0, 4.5, 'Bülach', 'Switzerland', 'Zurich'),
('Industrial Garden Apartment in Sion', 'Charming old building with high ceilings and stucco details. Surrounded by nature, perfect for outdoor enthusiasts.', 3986.0, 3.5, 'Sion', 'Switzerland', 'Valais'),
('Quiet Studio in Zug', 'Features a modern kitchen, large balcony, and underground parking. Ideal for families or professionals. Close to schools and shops.', 13542.0, 2, 'Zug', 'Switzerland', 'Zug'),
('Affordable House in Wetzikon', 'Charming old building with high ceilings and stucco details. Luxury amenities including concierge service and gym access.', 2653.0, 4.5, 'Wetzikon', 'Switzerland', 'Zurich'),
('Premium Duplex in Grenchen', 'Luxury amenities including concierge service and gym access. Smart home features and energy efficient construction.', 10924.0, 2.5, 'Grenchen', 'Switzerland', 'Solothurn'),
('Quiet Garden Apartment in Monthey', 'In the heart of the city, walking distance to the train station. Charming old building with high ceilings and stucco details.', 2392.0, 2.5, 'Monthey', 'Switzerland', 'Valais'),
('Renovated Residence in Sarnen', 'Smart home features and energy efficient construction. Charming old building with high ceilings and stucco details.', 3441.0, 1.5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Minimalist Studio in Brugg', 'Ideal for families or professionals. Close to schools and shops. Ideal for families or professionals. Close to schools and shops.', 6655.0, 3, 'Brugg', 'Switzerland', 'Aargau'),
('Charming Attic in Stans', 'Spacious living room with fireplace and open plan kitchen. Smart home features and energy efficient construction.', 13882.0, 1, 'Stans', 'Switzerland', 'Nidwalden'),
('Central Terrace Flat in Kloten', 'Private garden and patio area. Pet friendly. Located in a quiet neighborhood with easy access to public transport.', 6451.0, 2.5, 'Kloten', 'Switzerland', 'Zurich'),
('Historic Flat in Vevey', 'Features a modern kitchen, large balcony, and underground parking. Located in a quiet neighborhood with easy access to public transport.', 6493.0, 1.5, 'Vevey', 'Switzerland', 'Vaud'),
('Renovated Penthouse in Delémont', 'Private garden and patio area. Pet friendly. Features a modern kitchen, large balcony, and underground parking.', 6663.0, 1.5, 'Delémont', 'Switzerland', 'Jura'),
('Minimalist Loft in Wohlen', 'Private garden and patio area. Pet friendly. Recently renovated with attention to detail. Wood floors throughout.', 12163.0, 3.5, 'Wohlen', 'Switzerland', 'Aargau'),
('Luxury Chalet in Sierre', 'Top floor with elevator and panoramic terrace. Stunning views of the mountains and lake. High-end finishing.', 3120.0, 4.5, 'Sierre', 'Switzerland', 'Valais'),
('Cozy Loft in Uster', 'Spacious living room with fireplace and open plan kitchen. Charming old building with high ceilings and stucco details.', 3018.0, 1, 'Uster', 'Switzerland', 'Zurich'),
('Stylish Terrace Flat in Bülach', 'Features a modern kitchen, large balcony, and underground parking. Cozy retreat for weekend getaways or permanent living.', 9744.0, 4.5, 'Bülach', 'Switzerland', 'Zurich'),
('Charming Chalet in Altdorf', 'In the heart of the city, walking distance to the train station. In the heart of the city, walking distance to the train station.', 12661.0, 3.5, 'Altdorf', 'Switzerland', 'Uri'),
('Spacious Chalet in Fribourg', 'Recently renovated with attention to detail. Wood floors throughout. Bright rooms with floor-to-ceiling windows.', 13607.0, 5, 'Fribourg', 'Switzerland', 'Fribourg'),
('Renovated Loft in Davos', 'Located in a quiet neighborhood with easy access to public transport. Top floor with elevator and panoramic terrace.', 14048.0, 4, 'Davos', 'Switzerland', 'Grisons'),
('Stylish Apartment in Sarnen', 'Located in a quiet neighborhood with easy access to public transport. Surrounded by nature, perfect for outdoor enthusiasts.', 7869.0, 5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Stylish Apartment in Vevey', 'Cozy retreat for weekend getaways or permanent living. Top floor with elevator and panoramic terrace.', 1282.0, 3.5, 'Vevey', 'Switzerland', 'Vaud'),
('Sunny Apartment in Kloten', 'Spacious living room with fireplace and open plan kitchen. Bright rooms with floor-to-ceiling windows.', 3959.0, 3.5, 'Kloten', 'Switzerland', 'Zurich'),
('Charming Flat in Fribourg', 'Charming old building with high ceilings and stucco details. Ideal for families or professionals. Close to schools and shops.', 2495.0, 2.5, 'Fribourg', 'Switzerland', 'Fribourg'),
('Bright Attic in Morges', 'Bright rooms with floor-to-ceiling windows. Stunning views of the mountains and lake. High-end finishing.', 4230.0, 3, 'Morges', 'Switzerland', 'Vaud'),
('Industrial Villa in Sierre', 'Private garden and patio area. Pet friendly. Spacious living room with fireplace and open plan kitchen.', 2458.0, 5, 'Sierre', 'Switzerland', 'Valais'),
('Central Attic in Bülach', 'Stunning views of the mountains and lake. High-end finishing. Features a modern kitchen, large balcony, and underground parking.', 10344.0, 1.5, 'Bülach', 'Switzerland', 'Zurich'),
('Sunny Penthouse in Landquart', 'Spacious living room with fireplace and open plan kitchen. Smart home features and energy efficient construction.', 10994.0, 4, 'Landquart', 'Switzerland', 'Grisons'),
('Exclusive Studio in Fribourg', 'Private garden and patio area. Pet friendly. Located in a quiet neighborhood with easy access to public transport.', 8249.0, 2, 'Fribourg', 'Switzerland', 'Fribourg'),
('Traditional Studio in Herisau', 'Spacious living room with fireplace and open plan kitchen. Spacious living room with fireplace and open plan kitchen.', 12771.0, 1.5, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Premium Apartment in Wetzikon', 'Recently renovated with attention to detail. Wood floors throughout. Top floor with elevator and panoramic terrace.', 11749.0, 5, 'Wetzikon', 'Switzerland', 'Zurich'),
('Affordable Apartment in Monthey', 'Located in a quiet neighborhood with easy access to public transport. Bright rooms with floor-to-ceiling windows.', 11610.0, 1, 'Monthey', 'Switzerland', 'Valais'),
('Historic Villa in Fribourg', 'Spacious living room with fireplace and open plan kitchen. In the heart of the city, walking distance to the train station.', 3164.0, 2, 'Fribourg', 'Switzerland', 'Fribourg'),
('Premium Garden Apartment in Morges', 'Charming old building with high ceilings and stucco details. Ideal for families or professionals. Close to schools and shops.', 4986.0, 4, 'Morges', 'Switzerland', 'Vaud'),
('Elegant Maisonette in Herisau', 'Spacious living room with fireplace and open plan kitchen. Recently renovated with attention to detail. Wood floors throughout.', 10706.0, 4, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Spacious Villa in Glarus', 'In the heart of the city, walking distance to the train station. In the heart of the city, walking distance to the train station.', 8922.0, 2, 'Glarus', 'Switzerland', 'Glarus'),
('Luxury Garden Apartment in Uster', 'Cozy retreat for weekend getaways or permanent living. Surrounded by nature, perfect for outdoor enthusiasts.', 8714.0, 3, 'Uster', 'Switzerland', 'Zurich'),
('Rustic Chalet in Chiasso', 'Charming old building with high ceilings and stucco details. Smart home features and energy efficient construction.', 5181.0, 3, 'Chiasso', 'Switzerland', 'Ticino'),
('Modern House in Vevey', 'Recently renovated with attention to detail. Wood floors throughout. Features a modern kitchen, large balcony, and underground parking.', 2451.0, 2, 'Vevey', 'Switzerland', 'Vaud'),
('Charming Duplex in Rapperswil-Jona', 'Stunning views of the mountains and lake. High-end finishing. Located in a quiet neighborhood with easy access to public transport.', 8510.0, 1.5, 'Rapperswil-Jona', 'Switzerland', 'St. Gallen'),
('Modern Duplex in Bülach', 'Surrounded by nature, perfect for outdoor enthusiasts. Charming old building with high ceilings and stucco details.', 5883.0, 4.5, 'Bülach', 'Switzerland', 'Zurich'),
('Minimalist Studio in Altdorf', 'Located in a quiet neighborhood with easy access to public transport. Top floor with elevator and panoramic terrace.', 10347.0, 5, 'Altdorf', 'Switzerland', 'Uri'),
('Modern Flat in Landquart', 'Cozy retreat for weekend getaways or permanent living. Smart home features and energy efficient construction.', 6418.0, 3.5, 'Landquart', 'Switzerland', 'Grisons'),
('Sunny Studio in Davos', 'In the heart of the city, walking distance to the train station. Charming old building with high ceilings and stucco details.', 3108.0, 1, 'Davos', 'Switzerland', 'Grisons'),
('Modern Studio in Morges', 'Private garden and patio area. Pet friendly. Luxury amenities including concierge service and gym access.', 6205.0, 3.5, 'Morges', 'Switzerland', 'Vaud'),
('Cozy Duplex in Sarnen', 'In the heart of the city, walking distance to the train station. Spacious living room with fireplace and open plan kitchen.', 5149.0, 4.5, 'Sarnen', 'Switzerland', 'Obwalden'),
('Charming Garden Apartment in Brugg', 'Bright rooms with floor-to-ceiling windows. Luxury amenities including concierge service and gym access.', 1389.0, 3.5, 'Brugg', 'Switzerland', 'Aargau'),
('Central Loft in Davos', 'In the heart of the city, walking distance to the train station. Spacious living room with fireplace and open plan kitchen.', 5664.0, 2, 'Davos', 'Switzerland', 'Grisons'),
('Renovated Garden Apartment in Wohlen', 'Bright rooms with floor-to-ceiling windows. Cozy retreat for weekend getaways or permanent living.', 9812.0, 3.5, 'Wohlen', 'Switzerland', 'Aargau'),
('Sunny Duplex in Monthey', 'Ideal for families or professionals. Close to schools and shops. Surrounded by nature, perfect for outdoor enthusiasts.', 8079.0, 5, 'Monthey', 'Switzerland', 'Valais'),
('Renovated Villa in Herisau', 'Bright rooms with floor-to-ceiling windows. Features a modern kitchen, large balcony, and underground parking.', 3090.0, 4.5, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Rustic Chalet in Sierre', 'Spacious living room with fireplace and open plan kitchen. Features a modern kitchen, large balcony, and underground parking.', 1986.0, 1, 'Sierre', 'Switzerland', 'Valais'),
('Historic Apartment in Bülach', 'Ideal for families or professionals. Close to schools and shops. Ideal for families or professionals. Close to schools and shops.', 12087.0, 3.5, 'Bülach', 'Switzerland', 'Zurich'),
('Rustic Garden Apartment in Neuchâtel', 'Recently renovated with attention to detail. Wood floors throughout. Luxury amenities including concierge service and gym access.', 9604.0, 3, 'Neuchâtel', 'Switzerland', 'Neuchâtel'),
('Stylish Villa in Brugg', 'Located in a quiet neighborhood with easy access to public transport. Features a modern kitchen, large balcony, and underground parking.', 4468.0, 4, 'Brugg', 'Switzerland', 'Aargau'),
('Sunny Duplex in Vevey', 'Surrounded by nature, perfect for outdoor enthusiasts. Located in a quiet neighborhood with easy access to public transport.', 12816.0, 4.5, 'Vevey', 'Switzerland', 'Vaud'),
('Rustic Studio in Vevey', 'Surrounded by nature, perfect for outdoor enthusiasts. Ideal for families or professionals. Close to schools and shops.', 8130.0, 3.5, 'Vevey', 'Switzerland', 'Vaud'),
('Industrial Flat in Zug', 'Ideal for families or professionals. Close to schools and shops. Private garden and patio area. Pet friendly.', 6692.0, 2.5, 'Zug', 'Switzerland', 'Zug'),
('Historic Chalet in Baden', 'Spacious living room with fireplace and open plan kitchen. Ideal for families or professionals. Close to schools and shops.', 6309.0, 1, 'Baden', 'Switzerland', 'Aargau'),
('Spacious Apartment in Delémont', 'Recently renovated with attention to detail. Wood floors throughout. Cozy retreat for weekend getaways or permanent living.', 6675.0, 2, 'Delémont', 'Switzerland', 'Jura'),
('Luxury Studio in Bülach', 'Ideal for families or professionals. Close to schools and shops. Bright rooms with floor-to-ceiling windows.', 9259.0, 5, 'Bülach', 'Switzerland', 'Zurich'),
('Industrial Terrace Flat in Fribourg', 'Smart home features and energy efficient construction. Luxury amenities including concierge service and gym access.', 13971.0, 1, 'Fribourg', 'Switzerland', 'Fribourg'),
('Renovated Villa in Davos', 'In the heart of the city, walking distance to the train station. Stunning views of the mountains and lake. High-end finishing.', 9533.0, 5, 'Davos', 'Switzerland', 'Grisons'),
('Exclusive Apartment in Sion', 'Cozy retreat for weekend getaways or permanent living. Stunning views of the mountains and lake. High-end finishing.', 6678.0, 2, 'Sion', 'Switzerland', 'Valais'),
('Industrial Penthouse in Kloten', 'Charming old building with high ceilings and stucco details. Recently renovated with attention to detail. Wood floors throughout.', 13806.0, 1.5, 'Kloten', 'Switzerland', 'Zurich'),
('Quiet Residence in Zug', 'Features a modern kitchen, large balcony, and underground parking. Ideal for families or professionals. Close to schools and shops.', 10834.0, 3, 'Zug', 'Switzerland', 'Zug'),
('Exclusive Flat in Neuchâtel', 'Recently renovated with attention to detail. Wood floors throughout. Surrounded by nature, perfect for outdoor enthusiasts.', 1859.0, 1, 'Neuchâtel', 'Switzerland', 'Neuchâtel'),
('Sunny Attic in Sion', 'Smart home features and energy efficient construction. Charming old building with high ceilings and stucco details.', 8934.0, 1.5, 'Sion', 'Switzerland', 'Valais'),
('Luxury Studio in Chiasso', 'Recently renovated with attention to detail. Wood floors throughout. Private garden and patio area. Pet friendly.', 13149.0, 1, 'Chiasso', 'Switzerland', 'Ticino'),
('Central Maisonette in Herisau', 'Luxury amenities including concierge service and gym access. Features a modern kitchen, large balcony, and underground parking.', 9330.0, 3, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Rustic Residence in Sierre', 'Recently renovated with attention to detail. Wood floors throughout. Smart home features and energy efficient construction.', 3339.0, 3, 'Sierre', 'Switzerland', 'Valais'),
('Premium Loft in Sierre', 'Spacious living room with fireplace and open plan kitchen. Features a modern kitchen, large balcony, and underground parking.', 8515.0, 1.5, 'Sierre', 'Switzerland', 'Valais'),
('Industrial Penthouse in Chiasso', 'Private garden and patio area. Pet friendly. Ideal for families or professionals. Close to schools and shops.', 8010.0, 1.5, 'Chiasso', 'Switzerland', 'Ticino'),
('Cozy Garden Apartment in Bülach', 'Bright rooms with floor-to-ceiling windows. In the heart of the city, walking distance to the train station.', 9992.0, 3, 'Bülach', 'Switzerland', 'Zurich'),
('Quiet Villa in Zug', 'Bright rooms with floor-to-ceiling windows. Spacious living room with fireplace and open plan kitchen.', 7512.0, 4.5, 'Zug', 'Switzerland', 'Zug'),
('Renovated Studio in Glarus', 'Top floor with elevator and panoramic terrace. Stunning views of the mountains and lake. High-end finishing.', 12746.0, 4, 'Glarus', 'Switzerland', 'Glarus'),
('Quiet Maisonette in Glarus', 'Ideal for families or professionals. Close to schools and shops. Features a modern kitchen, large balcony, and underground parking.', 4001.0, 5, 'Glarus', 'Switzerland', 'Glarus'),
('Premium Penthouse in Kloten', 'In the heart of the city, walking distance to the train station. Bright rooms with floor-to-ceiling windows.', 2926.0, 4, 'Kloten', 'Switzerland', 'Zurich'),
('Modern Studio in Davos', 'Cozy retreat for weekend getaways or permanent living. Cozy retreat for weekend getaways or permanent living.', 14639.0, 2.5, 'Davos', 'Switzerland', 'Grisons'),
('Bright Penthouse in Chiasso', 'Surrounded by nature, perfect for outdoor enthusiasts. Stunning views of the mountains and lake. High-end finishing.', 13093.0, 1, 'Chiasso', 'Switzerland', 'Ticino'),
('Cozy Attic in Delémont', 'Features a modern kitchen, large balcony, and underground parking. Cozy retreat for weekend getaways or permanent living.', 5858.0, 1, 'Delémont', 'Switzerland', 'Jura'),
('Modern Chalet in Davos', 'In the heart of the city, walking distance to the train station. Smart home features and energy efficient construction.', 8215.0, 5, 'Davos', 'Switzerland', 'Grisons'),
('Modern Flat in Delémont', 'Stunning views of the mountains and lake. High-end finishing. In the heart of the city, walking distance to the train station.', 4509.0, 3.5, 'Delémont', 'Switzerland', 'Jura'),
('Cozy Chalet in Grenchen', 'Spacious living room with fireplace and open plan kitchen. Charming old building with high ceilings and stucco details.', 7479.0, 5, 'Grenchen', 'Switzerland', 'Solothurn'),
('Affordable Terrace Flat in Grenchen', 'Private garden and patio area. Pet friendly. Smart home features and energy efficient construction.', 3450.0, 4, 'Grenchen', 'Switzerland', 'Solothurn'),
('Historic Villa in Davos', 'Spacious living room with fireplace and open plan kitchen. Luxury amenities including concierge service and gym access.', 2808.0, 4.5, 'Davos', 'Switzerland', 'Grisons'),
('Quiet Studio in Fribourg', 'Stunning views of the mountains and lake. High-end finishing. Cozy retreat for weekend getaways or permanent living.', 10934.0, 4, 'Fribourg', 'Switzerland', 'Fribourg'),
('Luxury Loft in Monthey', 'Smart home features and energy efficient construction. Located in a quiet neighborhood with easy access to public transport.', 9163.0, 5, 'Monthey', 'Switzerland', 'Valais'),
('Sunny Flat in Davos', 'In the heart of the city, walking distance to the train station. Smart home features and energy efficient construction.', 8375.0, 4.5, 'Davos', 'Switzerland', 'Grisons'),
('Minimalist Flat in Stans', 'Bright rooms with floor-to-ceiling windows. Luxury amenities including concierge service and gym access.', 8970.0, 4, 'Stans', 'Switzerland', 'Nidwalden'),
('Modern Flat in Fribourg', 'Smart home features and energy efficient construction. Private garden and patio area. Pet friendly.', 6382.0, 3, 'Fribourg', 'Switzerland', 'Fribourg'),
('Premium Terrace Flat in Kloten', 'Surrounded by nature, perfect for outdoor enthusiasts. Top floor with elevator and panoramic terrace.', 12342.0, 3, 'Kloten', 'Switzerland', 'Zurich'),
('Affordable Maisonette in Herisau', 'Ideal for families or professionals. Close to schools and shops. Located in a quiet neighborhood with easy access to public transport.', 2373.0, 3, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Exclusive House in Sierre', 'Ideal for families or professionals. Close to schools and shops. Bright rooms with floor-to-ceiling windows.', 2757.0, 3.5, 'Sierre', 'Switzerland', 'Valais'),
('Charming Studio in Monthey', 'Surrounded by nature, perfect for outdoor enthusiasts. Ideal for families or professionals. Close to schools and shops.', 8903.0, 1.5, 'Monthey', 'Switzerland', 'Valais'),
('Charming Villa in Sierre', 'Stunning views of the mountains and lake. High-end finishing. Surrounded by nature, perfect for outdoor enthusiasts.', 3983.0, 3, 'Sierre', 'Switzerland', 'Valais'),
('Affordable Studio in Monthey', 'In the heart of the city, walking distance to the train station. Cozy retreat for weekend getaways or permanent living.', 13239.0, 3, 'Monthey', 'Switzerland', 'Valais'),
('Charming Residence in Morges', 'Surrounded by nature, perfect for outdoor enthusiasts. Stunning views of the mountains and lake. High-end finishing.', 14265.0, 3.5, 'Morges', 'Switzerland', 'Vaud'),
('Elegant Apartment in Brugg', 'Charming old building with high ceilings and stucco details. Stunning views of the mountains and lake. High-end finishing.', 3236.0, 2, 'Brugg', 'Switzerland', 'Aargau'),
('Rustic Flat in Sarnen', 'Cozy retreat for weekend getaways or permanent living. Spacious living room with fireplace and open plan kitchen.', 3843.0, 3, 'Sarnen', 'Switzerland', 'Obwalden'),
('Quiet Chalet in Grenchen', 'Private garden and patio area. Pet friendly. Cozy retreat for weekend getaways or permanent living.', 10524.0, 2, 'Grenchen', 'Switzerland', 'Solothurn'),
('Quiet Attic in Wetzikon', 'Private garden and patio area. Pet friendly. Cozy retreat for weekend getaways or permanent living.', 14072.0, 1.5, 'Wetzikon', 'Switzerland', 'Zurich'),
('Affordable House in Glarus', 'Spacious living room with fireplace and open plan kitchen. Stunning views of the mountains and lake. High-end finishing.', 6683.0, 2.5, 'Glarus', 'Switzerland', 'Glarus'),
('Affordable House in Sion', 'Charming old building with high ceilings and stucco details. Recently renovated with attention to detail. Wood floors throughout.', 14962.0, 2.5, 'Sion', 'Switzerland', 'Valais'),
('Luxury Duplex in Brugg', 'Private garden and patio area. Pet friendly. Cozy retreat for weekend getaways or permanent living.', 4280.0, 3.5, 'Brugg', 'Switzerland', 'Aargau'),
('Renovated Loft in Monthey', 'Recently renovated with attention to detail. Wood floors throughout. Stunning views of the mountains and lake. High-end finishing.', 11058.0, 1, 'Monthey', 'Switzerland', 'Valais'),
('Sunny Flat in Brugg', 'Features a modern kitchen, large balcony, and underground parking. In the heart of the city, walking distance to the train station.', 1894.0, 5, 'Brugg', 'Switzerland', 'Aargau'),
('Elegant Villa in Morges', 'Smart home features and energy efficient construction. Surrounded by nature, perfect for outdoor enthusiasts.', 14613.0, 4, 'Morges', 'Switzerland', 'Vaud'),
('Minimalist Chalet in Wohlen', 'Luxury amenities including concierge service and gym access. Features a modern kitchen, large balcony, and underground parking.', 13211.0, 1.5, 'Wohlen', 'Switzerland', 'Aargau'),
('Renovated Residence in Landquart', 'Top floor with elevator and panoramic terrace. In the heart of the city, walking distance to the train station.', 2576.0, 4.5, 'Landquart', 'Switzerland', 'Grisons'),
('Bright Garden Apartment in Interlaken', 'Top floor with elevator and panoramic terrace. Recently renovated with attention to detail. Wood floors throughout.', 3755.0, 4, 'Interlaken', 'Switzerland', 'Bern'),
('Central Studio in Brugg', 'Smart home features and energy efficient construction. Recently renovated with attention to detail. Wood floors throughout.', 5473.0, 4, 'Brugg', 'Switzerland', 'Aargau'),
('Traditional Maisonette in Interlaken', 'Smart home features and energy efficient construction. Recently renovated with attention to detail. Wood floors throughout.', 9720.0, 3, 'Interlaken', 'Switzerland', 'Bern'),
('Exclusive Attic in Herisau', 'In the heart of the city, walking distance to the train station. Smart home features and energy efficient construction.', 7795.0, 5, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Affordable Penthouse in Bülach', 'In the heart of the city, walking distance to the train station. Located in a quiet neighborhood with easy access to public transport.', 2792.0, 1, 'Bülach', 'Switzerland', 'Zurich'),
('Sunny Flat in Wohlen', 'Charming old building with high ceilings and stucco details. Stunning views of the mountains and lake. High-end finishing.', 7906.0, 4, 'Wohlen', 'Switzerland', 'Aargau'),
('Elegant Maisonette in Chiasso', 'Features a modern kitchen, large balcony, and underground parking. Charming old building with high ceilings and stucco details.', 10042.0, 3.5, 'Chiasso', 'Switzerland', 'Ticino'),
('Minimalist Villa in Morges', 'Smart home features and energy efficient construction. Charming old building with high ceilings and stucco details.', 14327.0, 1.5, 'Morges', 'Switzerland', 'Vaud'),
('Elegant Garden Apartment in Delémont', 'Bright rooms with floor-to-ceiling windows. Private garden and patio area. Pet friendly.', 5936.0, 1, 'Delémont', 'Switzerland', 'Jura'),
('Sunny Residence in Chiasso', 'Charming old building with high ceilings and stucco details. Spacious living room with fireplace and open plan kitchen.', 7310.0, 5, 'Chiasso', 'Switzerland', 'Ticino'),
('Historic Chalet in Morges', 'Cozy retreat for weekend getaways or permanent living. Luxury amenities including concierge service and gym access.', 12569.0, 1.5, 'Morges', 'Switzerland', 'Vaud'),
('Premium Villa in Zug', 'Features a modern kitchen, large balcony, and underground parking. Luxury amenities including concierge service and gym access.', 1643.0, 2.5, 'Zug', 'Switzerland', 'Zug'),
('Stylish Loft in Glarus', 'In the heart of the city, walking distance to the train station. Surrounded by nature, perfect for outdoor enthusiasts.', 2771.0, 1, 'Glarus', 'Switzerland', 'Glarus'),
('Cozy Garden Apartment in Sierre', 'Cozy retreat for weekend getaways or permanent living. Stunning views of the mountains and lake. High-end finishing.', 6299.0, 3, 'Sierre', 'Switzerland', 'Valais'),
('Charming Maisonette in Wetzikon', 'Smart home features and energy efficient construction. Stunning views of the mountains and lake. High-end finishing.', 13751.0, 2, 'Wetzikon', 'Switzerland', 'Zurich'),
('Rustic Terrace Flat in Wetzikon', 'Surrounded by nature, perfect for outdoor enthusiasts. Private garden and patio area. Pet friendly.', 12668.0, 1.5, 'Wetzikon', 'Switzerland', 'Zurich'),
('Historic Villa in Wohlen', 'Cozy retreat for weekend getaways or permanent living. Surrounded by nature, perfect for outdoor enthusiasts.', 12987.0, 2.5, 'Wohlen', 'Switzerland', 'Aargau'),
('Rustic Studio in Landquart', 'Located in a quiet neighborhood with easy access to public transport. Smart home features and energy efficient construction.', 6035.0, 2.5, 'Landquart', 'Switzerland', 'Grisons'),
('Luxury Attic in Monthey', 'Smart home features and energy efficient construction. Charming old building with high ceilings and stucco details.', 8482.0, 2.5, 'Monthey', 'Switzerland', 'Valais'),
('Modern Flat in Morges', 'In the heart of the city, walking distance to the train station. Stunning views of the mountains and lake. High-end finishing.', 4278.0, 1, 'Morges', 'Switzerland', 'Vaud'),
('Cozy Terrace Flat in Wetzikon', 'Private garden and patio area. Pet friendly. Smart home features and energy efficient construction.', 10294.0, 3.5, 'Wetzikon', 'Switzerland', 'Zurich'),
('Quiet House in Stans', 'Luxury amenities including concierge service and gym access. Cozy retreat for weekend getaways or permanent living.', 10648.0, 4.5, 'Stans', 'Switzerland', 'Nidwalden'),
('Charming Attic in Interlaken', 'Ideal for families or professionals. Close to schools and shops. Smart home features and energy efficient construction.', 1797.0, 4.5, 'Interlaken', 'Switzerland', 'Bern'),
('Quiet Garden Apartment in Monthey', 'Charming old building with high ceilings and stucco details. In the heart of the city, walking distance to the train station.', 12583.0, 5, 'Monthey', 'Switzerland', 'Valais'),
('Spacious Apartment in Morges', 'Charming old building with high ceilings and stucco details. Luxury amenities including concierge service and gym access.', 13038.0, 2.5, 'Morges', 'Switzerland', 'Vaud'),
('Premium Loft in Herisau', 'Luxury amenities including concierge service and gym access. In the heart of the city, walking distance to the train station.', 6696.0, 4.5, 'Herisau', 'Switzerland', 'Appenzell Ausserrhoden'),
('Rustic Flat in Rapperswil-Jona', 'In the heart of the city, walking distance to the train station. Top floor with elevator and panoramic terrace.', 9382.0, 2, 'Rapperswil-Jona', 'Switzerland', 'St. Gallen'),
('Elegant Chalet in Monthey', 'Surrounded by nature, perfect for outdoor enthusiasts. Spacious living room with fireplace and open plan kitchen.', 6881.0, 1.5, 'Monthey', 'Switzerland', 'Valais'),
('Stylish House in Vevey', 'Recently renovated with attention to detail. Wood floors throughout. Features a modern kitchen, large balcony, and underground parking.', 8692.0, 1.5, 'Vevey', 'Switzerland', 'Vaud'),
('Premium Villa in Wohlen', 'Features a modern kitchen, large balcony, and underground parking. Features a modern kitchen, large balcony, and underground parking.', 13053.0, 3.5, 'Wohlen', 'Switzerland', 'Aargau'),
('Premium Flat in Kloten', 'In the heart of the city, walking distance to the train station. Bright rooms with floor-to-ceiling windows.', 13109.0, 2.5, 'Kloten', 'Switzerland', 'Zurich'),
('Minimalist House in Martigny', 'Features a modern kitchen, large balcony, and underground parking. Charming old building with high ceilings and stucco details.', 1779.0, 1, 'Martigny', 'Switzerland', 'Valais'),
('Affordable Loft in Morges', 'Private garden and patio area. Pet friendly. Cozy retreat for weekend getaways or permanent living.', 4374.0, 4, 'Morges', 'Switzerland', 'Vaud'),
('Luxury Garden Apartment in Chiasso', 'Spacious living room with fireplace and open plan kitchen. Spacious living room with fireplace and open plan kitchen.', 8888.0, 5, 'Chiasso', 'Switzerland', 'Ticino'),
('Traditional Residence in Zug', 'Private garden and patio area. Pet friendly. Charming old building with high ceilings and stucco details.', 14561.0, 3.5, 'Zug', 'Switzerland', 'Zug');
